name: yukicoder

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - containers
  - deepseq
  - integer-gmp
  - mtl
  - stm
  - text
  - time
  - transformers
  - vector

library:
  source-dirs:
    - lib
    - src

executables:
  yukicoder:
    main: Main.hs
    dependencies:
      - yukicoder